// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWo0Uf-b5KP59gygqbImv2QLnPSoBSSuw',
    appId: '1:969024558922:web:0b32b0e0c669f2b204d3b3',
    messagingSenderId: '969024558922',
    projectId: 'millenniummams-7fca8',
    authDomain: 'millenniummams-7fca8.firebaseapp.com',
    storageBucket: 'millenniummams-7fca8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjb351bqUhXIimeWhYUSXqqHO8OTMWjz8',
    appId: '1:969024558922:android:28d94ee06f178fd104d3b3',
    messagingSenderId: '969024558922',
    projectId: 'millenniummams-7fca8',
    storageBucket: 'millenniummams-7fca8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiI97zSzTGEuFPph6uEHc3aj2x3knl5uY',
    appId: '1:969024558922:ios:13cbe0b1293cfd0e04d3b3',
    messagingSenderId: '969024558922',
    projectId: 'millenniummams-7fca8',
    storageBucket: 'millenniummams-7fca8.appspot.com',
    iosBundleId: 'com.forcepower.multiClubApp',
  );

}